export const ADD_INGREDIENTS = 'ADD_INGREDIENTS';
export const REMOVE_INGREDIENTS = 'REMOVE_INGREDIENTS';
export const INITIATE_INGREDIENTS = 'INITIATE_INGREDIENTS';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';

export const PURCHASE_BURGER_INIT = 'PURCHASE_BURGER_INIT';
export const PERCHASE_BURGER_START = 'PERCHASE_BURGER_START';
export const PERCHASE_BURGER_SUCCESS = 'PERCHASE_BURGER_SUCCESS';
export const PERCHASE_BURGER_FAIL = 'PERCHASE_BURGER_FAIL';
export const PURCHASE_INIT = 'PURCHASE_INIT';

export const FETCH_ORDERS_INIT = 'FETCH_ORDERS_INIT';
export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';

export const AUTH_USER = 'AUTH_USER';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const SET_AUTH_REDIRECT = 'SET_AUTH_REDIRECT';
export const CHECK_AUTH_STATE = 'CHECK_AUTH_STATE';

export const INITIATE_LOGOUT = 'INITIATE_LOGOUT';
export const LOG_OUT = 'LOG_OUT';
